Name = "LzmaSdk"
Language = "C++"
Version = "19.0.0"
Interface = "CPP/Library/Module.cpp"
EnableWarningsAsErrors = false
Source = [
	"CPP/Library/ArchiveReader.cpp",
	"CPP/Library/ArchiveWriter.cpp",
	"C/7zCrc.c",
	"C/7zCrcOpt.c",
	"C/Alloc.c",
	"C/CpuArch.c",
	"C/LzFind.c",
	"C/LzFindMt.c",
	"C/Lzma2Dec.c",
	"C/Lzma2DecMt.c",
	"C/Lzma2Enc.c",
	"C/LzmaDec.c",
	"C/LzmaEnc.c",
	"C/MtCoder.c",
	"C/MtDec.c",
	"C/Threads.c",
	"CPP/7zip/Archive/7z/7zDecode.cpp",
	"CPP/7zip/Archive/7z/7zEncode.cpp",
	"CPP/7zip/Archive/7z/7zExtract.cpp",
	"CPP/7zip/Archive/7z/7zFolderInStream.cpp",
	"CPP/7zip/Archive/7z/7zHandler.cpp",
	"CPP/7zip/Archive/7z/7zHandlerOut.cpp",
	"CPP/7zip/Archive/7z/7zHeader.cpp",
	"CPP/7zip/Archive/7z/7zIn.cpp",
	"CPP/7zip/Archive/7z/7zOut.cpp",
	"CPP/7zip/Archive/7z/7zProperties.cpp",
	"CPP/7zip/Archive/7z/7zSpecStream.cpp",
	"CPP/7zip/Archive/7z/7zUpdate.cpp",
	"CPP/7zip/Archive/Common/CoderMixer2.cpp",
	"CPP/7zip/Archive/Common/HandlerOut.cpp",
	"CPP/7zip/Archive/Common/ItemNameUtils.cpp",
	"CPP/7zip/Common/CreateCoder.cpp",
	"CPP/7zip/Common/CWrappers.cpp",
	"CPP/7zip/Common/FilePathAutoRename.cpp",
	"CPP/7zip/Common/FileStreams.cpp",
	"CPP/7zip/Common/FilterCoder.cpp",
	"CPP/7zip/Common/InOutTempBuffer.cpp",
	"CPP/7zip/Common/LimitedStreams.cpp",
	"CPP/7zip/Common/MethodProps.cpp",
	"CPP/7zip/Common/OutBuffer.cpp",
	"CPP/7zip/Common/ProgressUtils.cpp",
	"CPP/7zip/Common/PropId.cpp",
	"CPP/7zip/Common/StreamBinder.cpp",
	"CPP/7zip/Common/StreamObjects.cpp",
	"CPP/7zip/Common/StreamUtils.cpp",
	"CPP/7zip/Common/UniqBlocks.cpp",
	"CPP/7zip/Common/VirtThread.cpp",
	"CPP/7zip/Compress/CopyCoder.cpp",
	"CPP/7zip/Compress/Lzma2Decoder.cpp",
	"CPP/7zip/Compress/Lzma2Encoder.cpp",
	"CPP/7zip/Compress/Lzma2Register.cpp",
	"CPP/7zip/Compress/LzmaDecoder.cpp",
	"CPP/7zip/Compress/LzmaEncoder.cpp",
	"CPP/7zip/Compress/LzmaRegister.cpp",
	"CPP/Common/IntToString.cpp",
	"CPP/Common/MyString.cpp",
	"CPP/Common/StringConvert.cpp",
	"CPP/Common/StringToInt.cpp",
	"CPP/Common/Wildcard.cpp",
	"CPP/Windows/ErrorMsg.cpp",
	"CPP/Windows/FileDir.cpp",
	"CPP/Windows/FileIO.cpp",
	"CPP/Windows/FileLink.cpp",
	"CPP/Windows/FileFind.cpp",
	"CPP/Windows/FileName.cpp",
	"CPP/Windows/PropVariant.cpp",
	"CPP/Windows/PropVariantConv.cpp",
	"CPP/Windows/System.cpp",
]