Name = "LzmaSdk"
Language = "C++"
Version = "19.0.0"
Interface = "Module.cpp"
EnableWarningsAsErrors = false
Source = [
	"ArchiveReader.cpp",
	"ArchiveWriter.cpp",
	"../../C/7zCrc.c",
	"../../C/7zCrcOpt.c",
	"../../C/Alloc.c",
	"../../C/CpuArch.c",
	"../../C/LzFind.c",
	"../../C/LzFindMt.c",
	"../../C/Lzma2Dec.c",
	"../../C/Lzma2DecMt.c",
	"../../C/Lzma2Enc.c",
	"../../C/LzmaDec.c",
	"../../C/LzmaEnc.c",
	"../../C/MtCoder.c",
	"../../C/MtDec.c",
	"../../C/Threads.c",
	"../7zip/Archive/7z/7zDecode.cpp",
	"../7zip/Archive/7z/7zEncode.cpp",
	"../7zip/Archive/7z/7zExtract.cpp",
	"../7zip/Archive/7z/7zFolderInStream.cpp",
	"../7zip/Archive/7z/7zHandler.cpp",
	"../7zip/Archive/7z/7zHandlerOut.cpp",
	"../7zip/Archive/7z/7zHeader.cpp",
	"../7zip/Archive/7z/7zIn.cpp",
	"../7zip/Archive/7z/7zOut.cpp",
	"../7zip/Archive/7z/7zProperties.cpp",
	"../7zip/Archive/7z/7zSpecStream.cpp",
	"../7zip/Archive/7z/7zUpdate.cpp",
	"../7zip/Archive/Common/CoderMixer2.cpp",
	"../7zip/Archive/Common/HandlerOut.cpp",
	"../7zip/Archive/Common/ItemNameUtils.cpp",
	"../7zip/Common/CreateCoder.cpp",
	"../7zip/Common/CWrappers.cpp",
	"../7zip/Common/FilePathAutoRename.cpp",
	"../7zip/Common/FileStreams.cpp",
	"../7zip/Common/FilterCoder.cpp",
	"../7zip/Common/InOutTempBuffer.cpp",
	"../7zip/Common/LimitedStreams.cpp",
	"../7zip/Common/MethodProps.cpp",
	"../7zip/Common/OutBuffer.cpp",
	"../7zip/Common/ProgressUtils.cpp",
	"../7zip/Common/PropId.cpp",
	"../7zip/Common/StreamBinder.cpp",
	"../7zip/Common/StreamObjects.cpp",
	"../7zip/Common/StreamUtils.cpp",
	"../7zip/Common/UniqBlocks.cpp",
	"../7zip/Common/VirtThread.cpp",
	"../7zip/Compress/CopyCoder.cpp",
	"../7zip/Compress/Lzma2Decoder.cpp",
	"../7zip/Compress/Lzma2Encoder.cpp",
	"../7zip/Compress/Lzma2Register.cpp",
	"../7zip/Compress/LzmaDecoder.cpp",
	"../7zip/Compress/LzmaEncoder.cpp",
	"../7zip/Compress/LzmaRegister.cpp",
	"../Common/IntToString.cpp",
	"../Common/MyString.cpp",
	"../Common/StringConvert.cpp",
	"../Common/StringToInt.cpp",
	"../Common/Wildcard.cpp",
	"../Windows/ErrorMsg.cpp",
	"../Windows/FileDir.cpp",
	"../Windows/FileIO.cpp",
	"../Windows/FileLink.cpp",
	"../Windows/FileFind.cpp",
	"../Windows/FileName.cpp",
	"../Windows/PropVariant.cpp",
	"../Windows/PropVariantConv.cpp",
	"../Windows/System.cpp",
]